import React from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { ArrowLeft } from 'lucide-react';

const modules = [
    {
      id: 1,
      title: 'Understanding Deepfakes',
      description: 'Learn about the technology behind deepfakes and how they are created.',
      content: `
        <p class="mb-4">Deepfakes represent a significant leap in artificial intelligence and synthetic media, with the power to create highly realistic, fabricated videos and audio recordings. The term itself is a portmanteau of "deep learning" and "fake," highlighting the sophisticated AI techniques used to generate this content. At its core, deepfake technology relies on a type of machine learning called a generative adversarial network (GAN), which involves two competing neural networks: a generator and a discriminator.</p>
        <p class="mb-4">The generator is responsible for creating the synthetic media, such as a video of a person saying or doing something they never did. It starts by producing random, low-quality images and gradually refines them based on feedback. The discriminator, on the other hand, acts as a detective. It is trained on a vast dataset of real images and videos, learning to distinguish between authentic and fake content. The two networks are locked in a constant battle: the generator strives to create fakes that are convincing enough to fool the discriminator, while the discriminator works to get better at spotting them. This adversarial process continues for thousands or even millions of iterations, with both networks improving over time. The end result is a generator that can produce incredibly realistic synthetic media, often indistinguishable from reality to the naked eye.</p>
        <p class="mb-4">The history of deepfakes is relatively short but has seen rapid advancements. The technology first gained widespread attention in late 2017 when a Reddit user began posting digitally altered pornographic videos featuring the faces of celebrities. While the initial use was malicious and nonconsensual, it showcased the power and accessibility of the underlying technology. Since then, deepfakes have evolved from a niche hobby into a sophisticated tool with a wide range of applications, both positive and negative. Early deepfakes were often easy to spot, with visual artifacts like flickering, unnatural facial movements, or a lack of blinking. However, as the technology has matured, these tell-tale signs have become increasingly rare, making detection a significant challenge.</p>
        <p class="mb-4">The potential applications of deepfakes are vast and varied. In the entertainment industry, the technology can be used to de-age actors, resurrect deceased performers for new roles, or seamlessly dub films into different languages with synchronized lip movements. It also has applications in education, where it could be used to create interactive historical figures or immersive training simulations. For example, medical students could practice complex surgical procedures on realistic virtual patients, or historians could bring ancient figures to life for a more engaging learning experience. In the world of accessibility, deepfakes could help individuals who have lost their voice to communicate in a synthesized version of their own speech, creating a more personal and natural-sounding alternative to generic text-to-speech systems.</p>
        <p class="mb-4">Despite these promising applications, the ethical concerns surrounding deepfakes are significant and cannot be overlooked. The technology's potential for misuse is vast, ranging from the creation of nonconsensual pornography and celebrity scandals to sophisticated financial fraud and political disinformation campaigns. Deepfake videos could be used to create fake evidence in a court case, manipulate stock prices by fabricating a CEO's statement, or incite social unrest by putting inflammatory words in a politician's mouth. The spread of such convincing misinformation could erode public trust in institutions, undermine democratic processes, and make it increasingly difficult for people to distinguish fact from fiction. As the technology becomes more accessible, the risk of it being used for personal revenge, bullying, or harassment also grows, posing a serious threat to individual privacy and security.</p>
        <p class="mb-4">Furthermore, the rise of deepfakes raises profound questions about the nature of truth and reality in the digital age. When we can no longer trust our own eyes and ears, how do we verify information and hold people accountable for their actions? The challenge of combating malicious deepfakes is not just a technical one; it also requires a multi-faceted approach involving media literacy education, robust verification standards, and clear legal frameworks. As we continue to navigate this new technological landscape, it is crucial to foster a public dialogue about the responsible development and deployment of AI, ensuring that we harness its benefits while mitigating its potential harms. Understanding the technology behind deepfakes is the first step in preparing for the complex challenges and opportunities they present.</p>
      `
    },
    {
      id: 2,
      title: 'Identifying Synthetic Media',
      description: 'Develop skills to spot deepfake content in images and videos.',
      content: `
        <p class="mb-4">As deepfake technology becomes more sophisticated, the ability to critically evaluate and identify synthetic media is an increasingly crucial skill for navigating the digital world. While AI-powered tools are being developed to assist in this process, human observation and critical thinking remain the first line of defense. Identifying synthetic media is not about spotting a single, definitive flaw, but rather about recognizing a collection of subtle inconsistencies and artifacts that, when taken together, suggest a piece of media may not be authentic. This process involves a combination of technical analysis, contextual evaluation, and an awareness of common manipulation techniques.</p>
        <h3 class="text-xl font-semibold text-white mb-2 mt-6">Technical and Visual Analysis</h3>
        <p class="mb-4">The most direct way to spot a deepfake is to look for visual and auditory imperfections left behind by the AI generation process. Although these artifacts are becoming rarer, they are often still present in less sophisticated fakes. When examining a video, pay close attention to the face. Unnatural facial movements are a common red flag. For example, the subject might blink infrequently or in an unnatural way, or their smile might not seem to engage the rest of their facial muscles. The edges of the face, particularly where it meets the hair or neck, can also be a giveaway. Look for blurring, distortion, or a subtle seam that suggests a face has been digitally grafted onto another person's head.</p>
        <p class="mb-4">Inconsistencies in lighting and shadows can also betray a deepfake. If a person's face is brightly lit from one side, but the shadows on their neck or the background don't match, it could be a sign of manipulation. Similarly, reflections in their eyes or on glasses should accurately reflect the surrounding environment. Awkward or unnatural head and body positioning is another indicator. The head might seem to be at a strange angle to the body, or the skin tone of the face might not perfectly match the rest of the body. In audio deepfakes, listen for a robotic or monotonous tone, unusual intonation, or a lack of the subtle background noise you would expect in a real recording.</p>
        <h3 class="text-xl font-semibold text-white mb-2 mt-6">Contextual Evaluation</h3>
        <p class="mb-4">Beyond visual analysis, understanding the context in which a piece of media is presented is vital. The first step is to consider the source. Is the video or image coming from a reputable news organization, or is it from an anonymous social media account with no history? Be wary of content that appears out of the blue and is designed to provoke a strong emotional reaction. A quick search for the story on established news sites can often reveal whether the media is authentic or part of a known disinformation campaign. If a shocking video of a public figure emerges, check to see if major news outlets are reporting on it. If they aren't, it's a good reason to be skeptical.</p>
        <p class="mb-4">Reverse image searching is another powerful tool for contextual analysis. By taking a screenshot of a video or uploading an image to a reverse image search engine, you can often find the original source of the media. This can reveal if an old video has been repurposed with a new, misleading caption, or if an image has been digitally altered. It's also important to consider the motive behind the media. Ask yourself: who benefits from this video being real? Is it designed to influence an election, damage someone's reputation, or sell a product? Understanding the potential agenda can help you approach the content with a healthy dose of skepticism.</p>
        <h3 class="text-xl font-semibold text-white mb-2 mt-6">The Role of AI and Future Challenges</h3>
        <p class="mb-4">As the technology for creating deepfakes improves, so too does the technology for detecting them. Researchers are developing sophisticated AI-powered tools that can analyze media for the subtle statistical artifacts that are invisible to the human eye. These tools can examine everything from pixel-level inconsistencies to the way light reflects off of a person's skin. However, this has led to an arms race: as detection tools get better, so do the deepfake generators, which learn to create fakes that can bypass the latest detection methods. This means that there will likely never be a foolproof technological solution for identifying all synthetic media.</p>
        <p class="mb-4">Ultimately, the most effective strategy for combating the threat of deepfakes is to foster a culture of media literacy and critical thinking. This means teaching people to question the media they consume, to seek out multiple sources, and to be aware of their own biases. It also involves a collective effort from social media platforms, news organizations, and policymakers to develop standards for authenticating and labeling media. While the challenge is significant, a combination of technological tools, contextual awareness, and a well-informed public can help us navigate the complexities of a world where seeing is no longer always believing.</p>
      `
    },
    {
      id: 3,
      title: 'Social Engineering Attacks',
      description: 'Understand how deepfakes are used in social engineering campaigns.',
      content: `
        <p class="mb-4">Social engineering is the art of psychological manipulation, where attackers exploit human trust, curiosity, and fear to trick individuals into divulging sensitive information or performing actions that compromise their security. Unlike traditional hacking, which targets vulnerabilities in software and hardware, social engineering targets the human element—often the weakest link in the security chain. Attackers rely on a set of well-established psychological principles, such as creating a sense of urgency, appealing to authority, or building a rapport of trust. The goal is to bypass technical security measures by turning a trusted insider into an unwitting accomplice. For years, this has been the foundation of phishing emails, pretexting phone calls, and baiting scams.</p>
        <h3 class="text-xl font-semibold text-white mb-2 mt-6">The New Frontier: Deepfakes in Social Engineering</h3>
        <p class="mb-4">The advent of deepfake technology has supercharged the potential of social engineering, adding a terrifying layer of authenticity to these manipulation tactics. Where attackers once relied on text-based emails or simple phone calls, they can now use hyper-realistic synthetic media to make their impersonations far more convincing. Deepfake audio, or voice cloning, can replicate a person's voice with stunning accuracy from just a small sample of their speech. This allows an attacker to move beyond simple vishing (voice phishing) and create a scenario where a victim genuinely believes they are speaking to a trusted colleague, family member, or authority figure. Similarly, deepfake videos can be used to create fabricated evidence, impersonate individuals in video calls, or craft highly convincing spear-phishing campaigns.</p>
        <h3 class="text-xl font-semibold text-white mb-2 mt-6">Common Attacks Amplified by Deepfakes</h3>
        <p class="mb-4"><strong>CEO Fraud and Business Email Compromise (BEC):</strong> This is one of the most alarming applications of deepfake technology in the corporate world. An attacker can use a voice clone of a CEO or another high-level executive to call an employee in the finance department and request an urgent, confidential wire transfer. By creating a sense of urgency and leveraging the authority of the executive's voice, the attacker can pressure the employee into bypassing normal security protocols. The request often comes with a plausible story, such as a secret acquisition or a time-sensitive payment to a new supplier, making it difficult for the employee to question its legitimacy.</p>
        <p class="mb-4"><strong>Vishing and Impersonation Scams:</strong> On a personal level, deepfake audio can make scams like the "grandparent scam" far more devastating. An elderly person might receive a call from a voice that sounds exactly like their grandchild, claiming to be in trouble and in desperate need of money. The emotional connection and the authentic-sounding voice can easily override any skepticism. This same technique can be used to impersonate bank officials, tax agents, or customer service representatives to trick individuals into handing over passwords, account numbers, or other personal information.</p>
        <p class="mb-4"><strong>Spear Phishing and Malware Distribution:</strong> Spear phishing is a targeted form of phishing that focuses on a specific individual or organization. Deepfakes can make these attacks incredibly effective. Imagine receiving an email from a colleague with a short video message attached. The video appears to be your colleague asking you to review an important document linked in the email. Because the video looks and sounds authentic, you are far more likely to click the link, which could lead to a malware infection or a credential-stealing website.</p>
        <h3 class="text-xl font-semibold text-white mb-2 mt-6">How to Defend Against Deepfake-Powered Social Engineering</h3>
        <p class="mb-4">Combating these advanced threats requires a shift in mindset and a reinforcement of security protocols. Since technology alone cannot solve the problem, the focus must be on human vigilance and verification.</p>
        <p class="mb-4"><strong>Establish Out-of-Band Verification:</strong> The single most effective defense is to verify unusual or high-stakes requests through a different communication channel. If you receive an urgent email from your boss asking for a wire transfer, don't just reply to the email. Call them on their known phone number or contact them through a trusted internal messaging app to confirm the request is legitimate. This secondary channel of communication makes it much harder for an attacker to maintain their impersonation.</p>
        <p class="mb-4"><strong>Be Skeptical of Urgency and Emotion:</strong> Social engineering attacks are designed to create a sense of panic and rush you into making a mistake. Any request that is both urgent and unusual should be treated with extreme suspicion. Take a moment to pause, think critically, and follow established procedures, no matter how much pressure you feel. If a request plays on your emotions—fear, sympathy, or excitement—it's a major red flag.</p>
        <p class="mb-4"><strong>Implement Challenge Questions or Codewords:</strong> For highly sensitive transactions or communications, consider establishing a system of challenge questions or codewords. This could be a pre-agreed-upon word or phrase that is used to verify identity during a phone or video call. While not foolproof, it adds another layer of security that can thwart an attacker who is relying solely on a deepfake.</p>
        <p class="mb-4"><strong>Continuous Employee Training:</strong> Organizations must invest in ongoing security awareness training that specifically addresses the threat of deepfakes. Employees should be shown examples of deepfake media and taught how to spot the subtle signs of manipulation. The more aware they are of the threat, the more likely they are to be cautious and follow security protocols.</p>
        <p class="mb-4">In conclusion, while deepfake technology has opened up new creative and practical possibilities, it has also armed social engineers with a powerful new weapon. The human element is more critical than ever, and fostering a culture of healthy skepticism and rigorous verification is our best defense in an increasingly synthetic world.</p>
      `
    },
    {
      id: 4,
      title: 'Phishing Awareness',
      description: 'Recognize and avoid phishing scams in emails, texts, and social media.',
      content: `
        <p class="mb-4">Phishing is one of the oldest and most enduring threats in the world of cybersecurity. At its core, it is a form of social engineering where an attacker attempts to trick a victim into voluntarily giving up sensitive information, such as usernames, passwords, credit card details, or social security numbers. The term "phishing" is a homophone of "fishing," and the analogy is apt: attackers bait a hook with a convincing-looking lure and cast it out to a wide audience, hoping someone will bite. These lures typically take the form of emails, text messages (a practice known as "smishing"), or direct messages on social media that appear to come from a legitimate and trusted source, such as a bank, a well-known company, or even a government agency.</p>
        <h3 class="text-xl font-semibold text-white mb-2 mt-6">The Anatomy of a Phishing Attack</h3>
        <p class="mb-4">A successful phishing attack usually follows a predictable pattern. It begins with a message designed to create a sense of urgency, fear, or curiosity. For example, an email might claim that your account has been compromised and you need to log in immediately to secure it. Another common tactic is to offer a reward, such as a prize or a discount, to entice you to click a link. The message will almost always contain a link or an attachment. The link will lead to a fraudulent website that is designed to look identical to the legitimate site it is impersonating. This spoofed website will have a login form where you are prompted to enter your credentials. Once you do, the attacker captures your information, and they can then use it to access your real account.</p>
        <p class="mb-4">If the message contains an attachment, it will likely be a malicious file disguised as something innocuous, like an invoice, a shipping confirmation, or an important document. Opening the attachment can install malware, such as ransomware or spyware, on your device. This malware can then be used to steal your personal information, encrypt your files for a ransom, or even give the attacker remote control over your computer.</p>
        <h3 class="text-xl font-semibold text-white mb-2 mt-6">Types of Phishing Attacks</h3>
        <p class="mb-4">While the basic principle of phishing remains the same, attackers have developed several variations to increase their chances of success:</p>
        <p class="mb-4"><strong>Spear Phishing:</strong> This is a highly targeted form of phishing that is directed at a specific individual or organization. Unlike the wide-net approach of traditional phishing, spear phishing attacks are carefully crafted using personal information about the target, which can be gathered from social media or other public sources. Because the message seems to come from a known and trusted source and contains personal details, it is far more convincing and has a much higher success rate.</p>
        <p class="mb-4"><strong>Whaling:</strong> Whaling is a type of spear phishing that specifically targets high-profile individuals within an organization, such as CEOs, CFOs, or other senior executives. The goal is to trick these individuals into authorizing large wire transfers or divulging confidential company information. The attacker might impersonate a lawyer, a business partner, or another executive to make their request seem legitimate.</p>
        <p class="mb-4"><strong>Vishing (Voice Phishing):</strong> As the name suggests, vishing uses the telephone to conduct phishing attacks. The attacker might use an automated voice message or a live person to try and trick you into giving up personal information. With the rise of deepfake audio technology, vishing has become even more dangerous, as attackers can now convincingly impersonate the voices of people you know and trust.</p>
        <h3 class="text-xl font-semibold text-white mb-2 mt-6">How to Spot a Phishing Attempt</h3>
        <p class="mb-4">Vigilance and skepticism are your best defenses against phishing. Here are some key red flags to look for:</p>
        <p class="mb-4"><strong>Check the Sender's Email Address:</strong> Don't just look at the display name; carefully examine the full email address. Phishing emails often use addresses that are very similar to the legitimate one, but with a slight misspelling or a different domain (e.g., "bankofamerica.co" instead of "bankofamerica.com").</p>
        <p class="mb-4"><strong>Look for Generic Greetings:</strong> Legitimate companies will usually address you by your name. Be wary of emails that use generic greetings like "Dear Customer" or "Valued Member."</p>
        <p class="mb-4"><strong>Hover Before You Click:</strong> Before you click on any link, hover your mouse over it to see the actual URL it will take you to. If the URL looks suspicious or doesn't match the context of the email, don't click it.</p>
        <p class="mb-4"><strong>Beware of Urgency and Threats:</strong> Phishing emails often try to create a sense of panic to rush you into making a mistake. Be suspicious of any message that threatens to close your account or take other negative action if you don't respond immediately.</p>
        <p class="mb-4"><strong>Check for Spelling and Grammar Mistakes:</strong> While not always the case, many phishing emails are poorly written and contain obvious spelling and grammatical errors.</p>
        <h3 class="text-xl font-semibold text-white mb-2 mt-6">What to Do If You Suspect a Phishing Attack</h3>
        <p class="mb-4">If you receive a suspicious message, the most important thing is not to click on any links or open any attachments. Do not reply to the message. Instead, delete it. If the message appears to be from a company you do business with, you can contact them directly through their official website or phone number to verify its authenticity. If you think you may have already fallen for a phishing scam, you should immediately change your passwords for any affected accounts and monitor your financial statements for any unusual activity. By staying informed and vigilant, you can significantly reduce your risk of becoming a victim of phishing.</p>
      `
    },
    {
      id: 5,
      title: 'Password Security',
      description: 'Best practices for creating and managing strong, unique passwords.',
      content: `
        <p class="mb-4">In our increasingly digital lives, passwords serve as the primary gatekeepers to our most sensitive personal and financial information. From email and social media to online banking and cloud storage, nearly every aspect of our modern world is protected by a password. However, the very ubiquity of passwords has led to a widespread sense of "password fatigue," causing many people to adopt insecure practices that leave them vulnerable to attack. Understanding the principles of strong password security is not just a technical best practice; it is a fundamental aspect of personal digital hygiene and a critical defense against a wide range of cyber threats.</p>
        <h3 class="text-xl font-semibold text-white mb-2 mt-6">What Makes a Strong Password?</h3>
        <p class="mb-4">The strength of a password is determined by its resistance to being guessed or cracked by an attacker. Attackers use a variety of techniques to compromise passwords, including brute-force attacks (systematically trying every possible combination of characters), dictionary attacks (using a list of common words and phrases), and credential stuffing (using lists of leaked passwords from other data breaches). A strong password is one that can withstand these attacks. The key elements of a strong password are:</p>
        <p class="mb-4"><strong>Length:</strong> This is the single most important factor in password strength. Each additional character exponentially increases the number of possible combinations an attacker would have to try. While the minimum password length on many sites is still eight characters, security experts now recommend a minimum of 12 to 16 characters for any sensitive account.</p>
        <p class="mb-4"><strong>Complexity:</strong> A strong password should be a random mix of uppercase and lowercase letters, numbers, and symbols. This significantly increases the size of the character set, making brute-force attacks much more time-consuming and computationally expensive for an attacker.</p>
        <p class="mb-4"><strong>Uniqueness:</strong> Every online account you have should have its own unique password. Reusing passwords, even strong ones, is one of the most common and dangerous security mistakes. If one site you use suffers a data breach and your password is leaked, attackers will try that same password on all of your other accounts. This is the principle behind credential stuffing attacks.</p>
        <h3 class="text-xl font-semibold text-white mb-2 mt-6">Common Password Pitfalls to Avoid</h3>
        <p class="mb-4">Creating a strong password also means avoiding common patterns and personal information that are easy for an attacker to guess. You should never use:</p>
        <p class="mb-4"><strong>Personal Information:</strong> Your name, your pet's name, your birthday, your anniversary, or any other publicly available information about you.</p>
        <p class="mb-4"><strong>Common Words and Phrases:</strong> Simple dictionary words like "password," "dragon," or "sunshine" are among the first things an attacker will try.</p>
        <p class="mb-4"><strong>Sequential or Repeated Characters:</strong> Passwords like "12345678" or "aaaaaaaa" are extremely weak and can be cracked almost instantly.</p>
        <p class="mb-4"><strong>Keyboard Patterns:</strong> Patterns like "qwerty" or "asdfghjkl" are also very common and easy to guess.</p>
        <h3 class="text-xl font-semibold text-white mb-2 mt-6">The Power of Passphrases and Password Managers</h3>
        <p class="mb-4">Remembering a long, complex, and unique password for every single account is a nearly impossible task for the human brain. This is where two key strategies come into play: passphrases and password managers.</p>
        <p class="mb-4"><strong>Passphrases:</strong> Instead of trying to remember a random string of characters, it can be easier to remember a sentence. A passphrase is a sequence of words that is long, easy to remember, and surprisingly secure. For example, a phrase like "CorrectHorseBatteryStaple" is much stronger than a shorter, more complex password like "Tr0ub4dor&3." You can make a passphrase even stronger by adding numbers and symbols, such as "Correct-Horse-Battery-Staple-2!"</p>
        <p class="mb-4"><strong>Password Managers:</strong> A password manager is a secure, encrypted application designed to store and manage all of your passwords. You only need to remember one strong master password to unlock the manager. The manager can then automatically generate long, random, and unique passwords for all of your accounts and fill them in for you when you log in. This is widely considered the gold standard of password security, as it allows you to use incredibly strong passwords without having to remember them. Many password managers can also securely store other sensitive information, such as credit card numbers and secure notes.</p>
        <h3 class="text-xl font-semibold text-white mb-2 mt-6">The Final Layer: Multi-Factor Authentication</h3>
        <p class="mb-4">Even the strongest password can be compromised in a data breach. That's why it's crucial to enable multi-factor authentication (MFA) on any account that supports it. MFA adds a second layer of security by requiring you to provide a second piece of information in addition to your password. This could be a code from an authenticator app on your phone, a fingerprint or face scan, or a physical security key. Even if an attacker steals your password, they won't be able to access your account without this second factor.</p>
        <p class="mb-4">In conclusion, while it may seem like a hassle, taking the time to create and manage strong passwords is one of the most important steps you can take to protect yourself in the digital world. By combining long, complex, and unique passwords with the use of a password manager and multi-factor authentication, you can build a formidable defense against a wide range of cyber threats.</p>
      `
    },
    {
      id: 6,
      title: 'Two-Factor Authentication (2FA)',
      description: 'Learn how to add an extra layer of security to your online accounts.',
      content: `
        <p class="mb-4">In the landscape of digital security, the password has long been the standard for verifying a user's identity. However, as cyber threats have become more sophisticated, it is clear that a single password is often not enough to provide robust protection. Data breaches are increasingly common, and even the strongest, most unique password can be compromised. This is where two-factor authentication (2FA), a subset of multi-factor authentication (MFA), comes in. 2FA is a simple yet powerful security measure that adds a critical second layer of defense to your online accounts, making it significantly more difficult for unauthorized users to gain access, even if they have managed to steal your password.</p>
        <h3 class="text-xl font-semibold text-white mb-2 mt-6">How Two-Factor Authentication Works</h3>
        <p class="mb-4">The principle behind 2FA is to verify your identity using two different types of credentials, or "factors." These factors are typically categorized into three types:</p>
        <p class="mb-4"><strong>1. Something you know:</strong> This is the most common factor and includes things like a password, a PIN, or the answer to a security question.</p>
        <p class="mb-4"><strong>2. Something you have:</strong> This factor relies on you possessing a physical object. Examples include your smartphone (which can receive a code via SMS or an authenticator app), a physical security key (a small USB device), or a smart card.</p>
        <p class="mb-4"><strong>3. Something you are:</strong> This category, known as biometrics, includes unique physical traits. Common examples are your fingerprint, your face (used in facial recognition), or your voice.</p>
        <p class="mb-4">A true 2FA system requires you to provide two factors from two different categories. For example, when you log in to an account, you will first enter your password (something you know). Then, the system will prompt you to provide a second factor, such as a one-time code sent to your phone (something you have). Because an attacker is unlikely to have both your password and physical possession of your phone, your account remains secure even if your password is compromised.</p>
        <h3 class="text-xl font-semibold text-white mb-2 mt-6">Common Types of Two-Factor Authentication</h3>
        <p class="mb-4">There are several ways to implement 2FA, each with its own level of security and convenience:</p>
        <p class="mb-4"><strong>SMS-Based 2FA:</strong> This is one of the most common and user-friendly methods. When you log in, a one-time code is sent to your phone via a text message. While this is far better than no 2FA at all, it is considered the least secure method. SMS messages can be intercepted, and an attacker could potentially perform a "SIM swap" attack, where they trick your mobile carrier into transferring your phone number to a new SIM card that they control.</p>
        <p class="mb-4"><strong>Authenticator Apps:</strong> This is a more secure and widely recommended method. You install an authenticator app (such as Google Authenticator, Microsoft Authenticator, or Authy) on your smartphone. When you set up 2FA on a new account, you scan a QR code to link the account to the app. The app will then generate a new, time-based one-time password (TOTP) every 30-60 seconds. Because the codes are generated on your device and are not transmitted over the mobile network, they are not vulnerable to interception in the same way that SMS codes are.</p>
        <p class="mb-4"><strong>Push Notifications:</strong> Some services offer an even more convenient method where, after you enter your password, a push notification is sent to your phone. You can then simply tap "Approve" or "Deny" to complete the login. This is both user-friendly and secure, as it often includes information about the location of the login attempt.</p>
        <p class="mb-4"><strong>Physical Security Keys:</strong> This is the most secure form of 2FA currently available. A security key is a small hardware device that you plug into your computer's USB port or connect via NFC to your phone. When prompted, you simply touch a button on the key to verify your identity. This method is resistant to both phishing and man-in-the-middle attacks, as the key communicates directly with the service and verifies that you are on the legitimate website.</p>
        <h3 class="text-xl font-semibold text-white mb-2 mt-6">Why You Should Use 2FA Everywhere</h3>
        <p class="mb-4">The importance of enabling 2FA on all of your sensitive accounts cannot be overstated. Your email account, in particular, should be your top priority, as it is often the key to resetting the passwords for all of your other accounts. If an attacker gains access to your email, they can initiate a password reset for your online banking, social media, and other critical services. Social media accounts are also a prime target, as they can be used to spread scams or misinformation to your friends and followers. Any service that stores your financial information, such as online banking or e-commerce sites, should also have 2FA enabled.</p>
        <p class="mb-4">While it may seem like a small inconvenience to enter a second code when you log in, the security benefits are immense. In a world where data breaches are a constant threat, 2FA provides a powerful and essential layer of protection. It is one of the single most effective steps you can take to secure your digital life, turning a compromised password from a potential catastrophe into a minor inconvenience.</p>
      `
    },
    {
      id: 7,
      title: 'Malware Protection',
      description: 'Protect your devices from viruses, ransomware, and other malicious software.',
      content: `
        <p class="mb-4">Malware, short for "malicious software," is a broad term that refers to any software intentionally designed to cause damage to a computer, server, client, or computer network. It is one of the most pervasive and varied threats in the digital world, created by cybercriminals to steal information, disrupt operations, or hold data for ransom. Malware can infect a wide range of devices, from traditional desktop computers and laptops to smartphones and other internet-connected devices. Understanding the different types of malware and how they spread is the first step in building a robust defense to protect your digital life from these insidious threats.</p>
        <h3 class="text-xl font-semibold text-white mb-2 mt-6">Common Types of Malware</h3>
        <p class="mb-4">The world of malware is diverse, with each type designed to achieve a specific malicious goal. Some of the most common types include:</p>
        <p class="mb-4"><strong>Viruses:</strong> A computer virus is a type of malware that, when executed, replicates itself by modifying other computer programs and inserting its own code. Viruses often spread from one computer to another through infected email attachments, downloaded files, or removable media like USB drives. They can perform a variety of harmful actions, such as corrupting or deleting data, or even taking control of a user's computer.</p>
        <p class="mb-4"><strong>Worms:</strong> Similar to viruses, worms are self-replicating programs. However, a key difference is that worms can spread across computer networks on their own, without any human interaction. They often exploit vulnerabilities in software to propagate from one machine to another, and they can cause widespread disruption by consuming bandwidth and overloading networks.</p>
        <p class="mb-4"><strong>Trojans (Trojan Horses):</strong> A Trojan is a type of malware that disguises itself as a legitimate program or file. An unsuspecting user is tricked into downloading and executing the Trojan, which then carries out its malicious function in the background. Unlike viruses and worms, Trojans do not replicate themselves. They are often used to create a "backdoor" on a user's computer, giving the attacker remote access to steal information or install other forms of malware.</p>
        <p class="mb-4"><strong>Ransomware:</strong> This is one of the most destructive and high-profile forms of malware. Ransomware works by encrypting the files on a victim's computer, making them inaccessible. The attacker then demands a ransom payment, usually in cryptocurrency, in exchange for the decryption key. There is no guarantee that paying the ransom will result in the files being restored, and a ransomware attack can be devastating for both individuals and organizations.</p>
        <p class="mb-4"><strong>Spyware:</strong> As the name suggests, spyware is designed to secretly monitor a user's activity on their computer. It can log keystrokes to capture passwords and other sensitive information, record browsing habits, and collect personal data without the user's knowledge or consent. This information can then be sold to third parties or used for identity theft.</p>
        <p class="mb-4"><strong>Adware:</strong> While often more annoying than malicious, adware is a type of software that automatically displays or downloads advertising material when a user is online. In some cases, adware can also be used to collect user data or redirect a user to malicious websites.</p>
        <h3 class="text-xl font-semibold text-white mb-2 mt-6">How Malware Spreads</h3>
        <p class="mb-4">Malware can infect a device through a variety of channels. Some of the most common infection vectors include:</p>
        <p class="mb-4"><strong>Phishing Emails:</strong> This is one of the most common ways malware is distributed. An attacker will send an email with a malicious attachment or a link to a compromised website. If the user opens the attachment or clicks the link, the malware is downloaded onto their device.</p>
        <p class="mb-4"><strong>Malicious Websites and Drive-By Downloads:</strong> A user can get infected with malware simply by visiting a compromised website. In a "drive-by download," malware is automatically downloaded and installed on the user's computer without their knowledge, often by exploiting a vulnerability in their web browser.</p>
        <p class="mb-4"><strong>Software Vulnerabilities:</strong> Cybercriminals are constantly looking for security holes in popular software, such as operating systems, web browsers, and applications. If a user has not installed the latest security patches, an attacker can exploit these vulnerabilities to install malware on their system.</p>
        <p class="mb-4"><strong>Removable Media:</strong> Malware can easily spread through infected USB drives, external hard drives, or other removable media. If an infected drive is plugged into a computer, the malware can be transferred to the new device.</p>
        <h3 class="text-xl font-semibold text-white mb-2 mt-6">Best Practices for Malware Protection</h3>
        <p class="mb-4">Protecting your devices from malware requires a multi-layered approach to security:</p>
        <p class="mb-4"><strong>Install and Maintain Antivirus Software:</strong> A reputable antivirus program is an essential tool for detecting and removing malware. Make sure your antivirus software is always running and that it is set to update automatically to protect you from the latest threats.</p>
        <p class="mb-4"><strong>Keep Your Software and Operating System Updated:</strong> Software updates often contain critical security patches that fix vulnerabilities. Enable automatic updates for your operating system and all of your applications to ensure you are always protected.</p>
        <p class="mb-4"><strong>Be Cautious with Emails and Attachments:</strong> Think before you click. Be wary of unsolicited emails, especially those that contain attachments or links. If an email seems suspicious, it's best to delete it without opening it.</p>
        <p class="mb-4"><strong>Use a Firewall:</strong> A firewall acts as a barrier between your computer and the internet, and it can help prevent unauthorized access to your device. Most modern operating systems have a built-in firewall, so make sure it is enabled.</p>
        <p class="mb-4"><strong>Practice Safe Browsing:</strong> Be careful about the websites you visit and the files you download. Avoid clicking on pop-up ads, and only download software from trusted sources.</p>
        <p class="mb-4"><strong>Back Up Your Data Regularly:</strong> In the event of a ransomware attack, having a recent backup of your important files can be the difference between a minor inconvenience and a major disaster. Make sure you back up your data to an external hard drive or a cloud-based service on a regular basis.</p>
        <p class="mb-4">By following these best practices, you can significantly reduce your risk of a malware infection and keep your personal information safe and secure.</p>
      `
    },
    {
      id: 8,
      title: 'Secure Wi-Fi Usage',
      description: 'Tips for safely connecting to public and private Wi-Fi networks.',
      content: `
        <p class="mb-4">In our hyper-connected world, the convenience of public Wi-Fi is undeniable. From coffee shops and airports to hotels and libraries, free wireless internet access has become a ubiquitous part of modern life, allowing us to stay productive and entertained on the go. However, this convenience comes with significant security risks. Public Wi-Fi networks are, by their nature, open and often unsecured, making them a prime hunting ground for cybercriminals looking to intercept data, steal personal information, and distribute malware. Understanding these risks and adopting safe browsing habits is essential for protecting your digital privacy and security whenever you connect to a public network.</p>
        <h3 class="text-xl font-semibold text-white mb-2 mt-6">The Dangers of Public Wi-Fi</h3>
        <p class="mb-4">The primary danger of public Wi-Fi lies in its lack of encryption. When you connect to a secure network, like your home Wi-Fi, the data that travels between your device and the router is encrypted, making it unreadable to anyone who might be trying to eavesdrop. Many public Wi-Fi networks, however, are unencrypted, meaning that any data you send or receive is transmitted in plain text. This creates several opportunities for attackers:</p>
        <p class="mb-4"><strong>Man-in-the-Middle (MitM) Attacks:</strong> This is one of the most common threats on public Wi-Fi. An attacker can position themselves between your device and the Wi-Fi router, allowing them to intercept, read, and even modify all of the data that passes between them. This can include your emails, login credentials, and credit card numbers. The attacker can do this by setting up their own malicious Wi-Fi hotspot with a convincing name, a tactic known as an "evil twin" attack.</p>
        <p class="mb-4"><strong>Evil Twin Attacks:</strong> An attacker can set up a fraudulent Wi-Fi hotspot with a name that is very similar to the legitimate one (e.g., "CoffeeShop_Free_Wi-Fi" instead of "CoffeeShop_Free_Wifi"). When you connect to this evil twin network, all of your internet traffic is routed through the attacker's device, giving them complete access to your data.</p>
        <p class="mb-4"><strong>Packet Sniffing:</strong> Using readily available software, an attacker on the same public network can "sniff" the wireless traffic, capturing the data packets that are being transmitted. If the network is unencrypted, the attacker can easily read the contents of these packets and extract sensitive information.</p>
        <p class="mb-4"><strong>Malware Distribution:</strong> Attackers can also use unsecured Wi-Fi networks to inject malware into your device. They might do this by redirecting you to a malicious website or by exploiting a software vulnerability to install malware directly onto your computer when you connect to the network.</p>
        <h3 class="text-xl font-semibold text-white mb-2 mt-6">Best Practices for Secure Wi-Fi Usage</h3>
        <p class="mb-4">While the risks are real, there are several steps you can take to protect yourself when using public Wi-Fi:</p>
        <p class="mb-4"><strong>Use a Virtual Private Network (VPN):</strong> This is the single most important tool for staying safe on public Wi-Fi. A VPN creates a secure, encrypted tunnel between your device and a remote server. All of your internet traffic is routed through this tunnel, making it unreadable to anyone who might be snooping on the network. Even if you are connected to a malicious hotspot, a VPN will keep your data safe.</p>
        <p class="mb-4"><strong>Verify the Network Name:</strong> Before you connect, make sure you are connecting to the official Wi-Fi network. If you are in a coffee shop or hotel, ask an employee for the exact name of their network. Be wary of any networks that have similar but slightly different names.</p>
        <p class="mb-4"><strong>Stick to HTTPS Websites:</strong> When you are browsing the web, look for "https" at the beginning of the URL and a padlock icon in the address bar. HTTPS indicates that the connection between your browser and the website is encrypted. While this doesn't protect all of your traffic, it does secure the data you exchange with that specific site. Most modern browsers will warn you if you are about to visit an unencrypted site.</p>
        <p class="mb-4"><strong>Disable File Sharing:</strong> Make sure that your device's file sharing settings are turned off before you connect to a public network. This will prevent other users on the network from being able to access the files on your computer.</p>
        <p class="mb-4"><strong>Keep Your Software Updated:</strong> As with malware protection, keeping your operating system and applications up to date is crucial. Software updates often contain security patches that can protect you from known vulnerabilities that attackers might try to exploit on a public network.</p>
        <p class="mb-4"><strong>Enable Your Firewall:</strong> A firewall can help block unauthorized access to your device. Make sure the firewall on your operating system is enabled before you connect to public Wi-Fi.</p>
        <p class="mb-4"><strong>Forget the Network When You're Done:</strong> Once you are finished using a public Wi-Fi network, it's a good practice to tell your device to "forget" it. This will prevent your device from automatically reconnecting to that network in the future without your knowledge.</p>
        <p class="mb-4">By treating all public Wi-Fi networks with a healthy dose of skepticism and following these best practices, you can enjoy the convenience of free internet access without putting your personal information at risk. A few simple precautions can make all the difference in keeping your digital life secure.</p>
      `
    },
    {
      id: 9,
      title: 'Data Privacy',
      description: 'Understand how to protect your personal information online and manage your digital footprint.',
      content: `
        <p class="mb-4">In the digital age, data has become one of the world's most valuable resources. Every time we go online, we leave behind a trail of digital footprints—from the websites we visit and the articles we read to the products we buy and the people we interact with. This data is collected, analyzed, and used by companies for a variety of purposes, from personalizing advertisements to developing new products. While this can lead to more convenient and customized online experiences, it also raises significant concerns about data privacy. Data privacy is not about hiding information; it is about having control over your personal data, including how it is collected, used, and shared. Understanding the principles of data privacy is essential for protecting your identity and maintaining your autonomy in an increasingly data-driven world.</p>
        <h3 class="text-xl font-semibold text-white mb-2 mt-6">Your Digital Footprint: What It Is and Why It Matters</h3>
        <p class="mb-4">Your digital footprint is the sum of all the data you create and leave behind as you use the internet. This can be divided into two categories: active and passive. Your active digital footprint includes the data you intentionally share, such as the posts you make on social media, the emails you send, and the online reviews you write. Your passive digital footprint, on the other hand, is the data you create without your direct intention, such as your IP address, your browsing history (collected via cookies), and your location data. Both types of data can be used to build a detailed profile of your interests, habits, and personal life. This profile can be used for targeted advertising, but it can also be used for more nefarious purposes, such as identity theft, surveillance, or manipulation.</p>
        <h3 class="text-xl font-semibold text-white mb-2 mt-6">The Role of Data Brokers and Big Tech</h3>
        <p class="mb-4">A vast and largely unregulated industry of data brokers operates in the shadows of the internet, buying, selling, and trading personal data. These companies collect information from a wide range of sources, including public records, social media, and online tracking cookies, to create detailed profiles of millions of individuals. These profiles can include everything from your age and income to your political affiliation and health concerns. Big tech companies also play a major role in the data economy, as their services are often designed to collect as much user data as possible. While these companies often provide valuable services for free, the trade-off is that they are constantly gathering information about your online behavior to sell to advertisers.</p>
        <h3 class="text-xl font-semibold text-white mb-2 mt-6">Data Breaches: The Inevitable Threat</h3>
        <p class="mb-4">A data breach occurs when sensitive or confidential information is accessed without authorization. Breaches can be the result of a direct cyberattack, such as a hack or a malware infection, or they can be the result of human error, such as an employee accidentally exposing a database to the internet. Data breaches are a constant threat, and even the largest and most well-resourced companies can fall victim. When a breach occurs, the personal information of millions of users can be leaked onto the dark web, where it can be bought and sold by cybercriminals. This information is often used to carry out identity theft, financial fraud, and other scams.</p>
        <h3 class="text-xl font-semibold text-white mb-2 mt-6">How to Protect Your Data Privacy</h3>
        <p class="mb-4">While it's impossible to be completely anonymous online, there are several practical steps you can take to protect your data privacy and manage your digital footprint:</p>
        <p class="mb-4"><strong>Be Mindful of What You Share:</strong> The simplest and most effective step is to be more conscious of the information you share online. Before you post something on social media or sign up for a new service, take a moment to consider whether you are comfortable with that information being public.</p>
        <p class="mb-4"><strong>Review and Adjust Your Privacy Settings:</strong> Most online services, including social media platforms and search engines, have detailed privacy settings that allow you to control how your data is collected and used. Take the time to go through these settings and customize them to a level you are comfortable with. For example, you can often limit the amount of data that is shared with third-party advertisers and turn off location tracking.</p>
        <p class="mb-4"><strong>Use a Privacy-Focused Browser and Search Engine:</strong> Mainstream web browsers and search engines are often designed to track your online activity. Consider using a privacy-focused browser, such as Firefox or Brave, which has built-in tracking protection. You can also switch to a search engine like DuckDuckGo, which does not track your search history.</p>
        <p class="mb-4"><strong>Use a VPN:</strong> As with secure Wi-Fi usage, a VPN is a powerful tool for data privacy. By encrypting your internet traffic and masking your IP address, a VPN makes it much more difficult for your internet service provider, data brokers, and other third parties to track your online activity.</p>
        <p class="mb-4"><strong>Manage Your Cookie Settings:</strong> Cookies are small text files that websites use to track your browsing habits. Most browsers allow you to block third-party cookies, which are the primary type used for cross-site tracking. You can also regularly clear your cookies to remove any existing tracking data.</p>
        <p class="mb-4"><strong>Exercise Your Rights:</strong> Depending on where you live, you may have legal rights over your data. Regulations like the General Data Protection Regulation (GDPR) in Europe and the California Consumer Privacy Act (CCPA) give individuals the right to access, correct, and delete the personal information that companies have collected about them. Be aware of your rights and don't be afraid to exercise them.</p>
        <p class="mb-4">By taking these proactive steps, you can regain a significant amount of control over your personal information. Data privacy is an ongoing effort, but by staying informed and making conscious choices about how you interact with the digital world, you can build a more secure and private online life.</p>
      `
    }
  ];

const ModuleDetail: React.FC = () => {
  const { moduleId } = useParams<{ moduleId: string }>();
  const navigate = useNavigate();
  const module = modules.find(m => m.id === parseInt(moduleId || ''));

  if (!module) {
    return (
      <div className="min-h-screen bg-gray-900 text-white p-8 pt-24">
        <div className="max-w-4xl mx-auto">
          <button onClick={() => navigate('/education')} className="flex items-center space-x-2 text-cyan-400 hover:text-cyan-300 mb-8">
          <ArrowLeft className="h-5 w-5" />
          <span>Back to Education</span>
        </button>
        <h1 className="text-4xl font-bold mb-4">Module not found</h1>
        <p>The requested module could not be found.</p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-900 text-white p-8 pt-24">
      <div className="max-w-4xl mx-auto">
        <button onClick={() => navigate('/education')} className="flex items-center space-x-2 text-cyan-400 hover:text-cyan-300 mb-8">
          <ArrowLeft className="h-5 w-5" />
          <span>Back to Education</span>
        </button>
        <h1 className="text-4xl font-bold mb-4">{module.title}</h1>
        <p className="text-lg text-gray-400 mb-8">{module.description}</p>
        <div className="bg-gray-800 rounded-lg p-6">
          <h2 className="text-2xl font-semibold mb-4">Module Content</h2>
          <div dangerouslySetInnerHTML={{ __html: module.content }} />
        </div>
      </div>
    </div>
  );
};

export default ModuleDetail;
