import React from 'react';
import { useParams } from 'react-router-dom';

const SecurityTipDetail: React.FC = () => {
  const { tipId } = useParams<{ tipId: string }>();

  // In a real application, you would fetch the tip details based on the tipId.
  // For now, we'll use placeholder content.
  const tipDetails = {
    'strong-passwords': {
      title: 'Use Strong Passwords',
      content: 'Creating a strong password is the first line of defense against unauthorized access to your accounts. A strong password should be long, complex, and unique. Avoid using easily guessable information like your name, birthday, or common words. Instead, use a mix of uppercase and lowercase letters, numbers, and symbols to create a password that is difficult to crack.',
      diagram: 'https://via.placeholder.com/600x400.png?text=Password+Security+Diagram'
    },
    'two-factor-authentication': {
      title: 'Enable Two-Factor Authentication',
      content: 'Two-factor authentication (2FA) adds a critical second layer of security to your accounts. Even if a hacker manages to steal your password, they won\'t be able to access your account without the second factor, which is typically a code sent to your phone or generated by an authenticator app. Enabling 2FA is one of the most effective ways to protect your online identity.',
      diagram: 'https://via.placeholder.com/600x400.png?text=2FA+Diagram'
    },
    'phishing-scams': {
      title: 'Beware of Phishing Scams',
      content: 'Phishing is a type of social engineering attack where attackers trick you into revealing sensitive information, such as passwords or credit card numbers. These scams often come in the form of emails or messages that appear to be from legitimate sources. Always be cautious of unsolicited requests for personal information and verify the sender\'s identity before clicking on any links or downloading attachments.',
      diagram: 'https://via.placeholder.com/600x400.png?text=Phishing+Scam+Diagram'
    },
    'keep-software-updated': {
      title: 'Keep Your Software Updated',
      content: 'Software updates are not just about adding new features; they also contain critical security patches that protect your devices from known vulnerabilities. Cybercriminals often exploit these vulnerabilities to install malware or steal your data. By regularly updating your operating system, web browser, and other applications, you can ensure that you have the latest security protections.',
      diagram: 'https://via.placeholder.com/600x400.png?text=Software+Update+Diagram'
    },
    'secure-wifi-network': {
      title: 'Secure Your Wi-Fi Network',
      content: 'Your home Wi-Fi network is a gateway to all your connected devices, so it\'s essential to secure it properly. Use a strong, unique password for your Wi-Fi network and enable WPA3 or WPA2 encryption. You should also change the default administrator password on your router to prevent unauthorized access. Avoid using public Wi-Fi networks for sensitive activities, as they are often unsecured.',
      diagram: 'https://via.placeholder.com/600x400.png?text=Wi-Fi+Security+Diagram'
    },
    'back-up-data': {
      title: 'Back Up Your Data',
      content: 'Data backups are your safety net in case of a cyberattack, hardware failure, or other unforeseen event. Regularly backing up your important files to an external hard drive or a secure cloud storage service ensures that you can recover your data if it is lost or encrypted by ransomware. A good backup strategy is a critical component of any personal cybersecurity plan.',
      diagram: 'https://via.placeholder.com/600x400.png?text=Data+Backup+Diagram'
    }
  };

  const tip = tipId ? tipDetails[tipId as keyof typeof tipDetails] : null;

  if (!tip) {
    return <div className="container mx-auto px-4 py-8 pt-24 text-center">Tip not found.</div>;
  }

  return (
    <div className="bg-gray-100 min-h-screen pt-24">
      <div className="container mx-auto px-4 py-8">
        <div className="bg-white p-8 rounded-lg shadow-md">
          <h1 className="text-4xl font-bold text-gray-800 mb-6 text-center">{tip.title}</h1>
          <p className="text-gray-600 text-lg mb-8">{tip.content}</p>
          <div className="flex justify-center">
            <img src={tip.diagram} alt={`${tip.title} Diagram`} className="rounded-lg shadow-md" />
          </div>
        </div>
      </div>
    </div>
  );
};

export default SecurityTipDetail;
